image: danbla/fuglutestenv

stages:
  - build
  - test_isolated
  - test
  - documentation

unittests:
  stage: test
  script:
    - cd fuglu
    - nosetests --rednose tests/unit
  only:
    - master
    - develop

isolated:
  stage: test_isolated
  script:
    - cd fuglu
    - nosetests --rednose tests/isolated --with-isolation
  only:
    - master
    - develop

unittests_py3:
  stage: test
  script:
    - cd fuglu
    - nosetests-3.4 --rednose tests/unit
  only:
    - master
    - develop

isolated_py3:
  stage: test_isolated
  script:
    - cd fuglu
    - nosetests-3.4 --rednose tests/isolated  --with-isolation
  only:
    - master
    - develop

integrationtests:
  stage: test
  script:
    - /usr/local/bin/start-services.sh
    - cd fuglu
    - nosetests --rednose tests/integration
  only:
    - master
    - develop

integrationtests_py3:
  stage: test
  script:
    - /usr/local/bin/start-services.sh
    - cd fuglu
    - nosetests-3.4 --rednose tests/integration
  only:
    - master
    - develop


# define RSYNC_TARGET in gitlab -> project domainmagic -> settings -> variables

buildfuglu:
  stage: build
  script:
    - cd fuglu
    - python setup.py build_py -d /tmp/build install --force
    - rename '.dist' '' /etc/fuglu/*.dist
    - mkdir -p /var/log/fuglu
    - chown nobody /var/log/fuglu
  only:
    - master
    - develop


buildfuglu_py3:
  stage: build
  script:
    - cd fuglu
    - python3 setup.py build_py -d /tmp/build install --force
    - rename '.dist' '' /etc/fuglu/*.dist
    - mkdir -p /var/log/fuglu
    - chown nobody /var/log/fuglu
  only:
    - master
    - develop

pages:
  image: alpine
  stage: documentation
  script:
  - mkdir public
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add make
  - cd documentation
  - make html
  - mv _build/* ../public/
  artifacts:
    paths:
    - public
  only:
    - master
    - documentation-masterbranch
