image: danbla/fuglutestenv

services:
   - name: redis:latest
     alias: tmpRedisDB

stages:
  - build
  - test_isolated
  - test
  - documentation
  - deploy

unittests:
  stage: test
  script:
    - cd fuglu
    - nosetests --rednose tests/unit
  except:
    - stack

isolated:
  stage: test_isolated
  script:
    - cd fuglu
    - nosetests --rednose tests/isolated --with-isolation
  except:
    - stack

unittests_py3:
  stage: test
  script:
    - cd fuglu
    - nosetests-3.6 --rednose tests/unit
  except:
    - stack

isolated_py3:
  stage: test_isolated
  script:
    - cd fuglu
    - nosetests-3.6 --rednose tests/isolated  --with-isolation
  except:
    - stack

integrationtests:
  stage: test
  script:
    - /usr/local/bin/start-services.sh
    - cd fuglu
    - nosetests --rednose tests/integration
  except:
    - stack

integrationtests_py3:
  stage: test
  script:
    - /usr/local/bin/start-services.sh
    - cd fuglu
    - nosetests-3.6 --rednose tests/integration
  except:
    - stack


# define RSYNC_TARGET in gitlab -> project fuglu -> settings -> variables

buildfuglu:
  stage: build
  script:
    - cd fuglu
    - python setup.py build_py -d /tmp/build install --force
    - rename '.dist' '' /etc/fuglu/*.dist
    - mkdir -p /var/log/fuglu
    - chown nobody /var/log/fuglu
  except:
    - stack


buildfuglu_py3:
  stage: build
  script:
    - cd fuglu
    - python3 setup.py build_py -d /tmp/build install --force
    - rename '.dist' '' /etc/fuglu/*.dist
    - mkdir -p /var/log/fuglu
    - chown nobody /var/log/fuglu
  except:
    - stack

pages:
  image: alpine
  stage: documentation
  script:
    - mkdir public
    - apk --no-cache add py2-pip python-dev make
    - cd fuglu
    - python setup.py install
    - cd develop/doc
    - ./make_sphinx_plugin_doc.py > ../../../documentation/source/includedplugins-autogen.txt
    - pip install sphinx
    - cd ../../../documentation
    - make html
    - mv _build/* ../public/
  artifacts:
    paths:
    - public
  only:
    - master
    - develop
    - milter
  except:
    - stack

# manual deploy option in gitlab
docker_deploy:
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  stage: deploy

  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CONTAINER_TEST_IMAGE_SHA: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  script:
    - ls -a
    - sh ./gitlab-ci-deploy.sh
  only:
    - stack
