version: '3'

services:
  clamd:
    build:
      context: ./.
      dockerfile: docker/clamd/Dockerfile
    image: fuglu:clamd

  spamd:
    build:
      context: ./.
      dockerfile: docker/spamd/Dockerfile
    image: fuglu:spamd

  redis:
    image: redis:latest

  fuglu:
    build:
      context: ./.
      dockerfile: docker/fuglu-testenv-contained/Dockerfile.alpine
    image: fuglu:fuglu
    depends_on:
      - clamd
      - spamd
      - redis
